name = "wakaway"
main = "src/index.ts"
compatibility_date = "2024-12-22"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
USERNAME = ""
PASSWORD = ""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "WAKAWAY"
database_name = "wakaway"
database_id = "bb6b5914-fcf2-44f4-b001-30eadc495bce"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1